// Иконки, которые можно выбрать в контенте (ключи — ICON_NAMES из схемы).
// Общие для лендинга и админки: в админке по ним рисуется выбор иконки.
import {
  Droplets,
  Layers,
  Leaf,
  Recycle,
  ShieldCheck,
  Sprout,
  Sun,
  Wind,
  Battery,
  Building2,
  Ruler,
  Weight,
  Grid2x2,
  Factory,
  FlaskConical,
  Headphones,
  Thermometer,
  CircleOff,
  Flower2,
  Globe2,
  HandHeart,
  Layers3,
  RefreshCcw,
  Shovel,
  Star,
  ThermometerSun,
  Waves,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/lib/content/schema";

export const ICONS = {
  droplet: Droplets,
  wind: Wind,
  sprout: Sprout,
  sun: Sun,
  weight: Weight,
  moss: Leaf,
  roof: Building2,
  battery: Battery,
  shield: ShieldCheck,
  recycle: Recycle,
  layers: Layers,
  porosity: Grid2x2,
  stable: Ruler,
  temperature: Thermometer,
  factory: Factory,
  flask: FlaskConical,
  headset: Headphones,
  circleOff: CircleOff,
  flower: Flower2,
  globe: Globe2,
  hand: HandHeart,
  layers3: Layers3,
  refresh: RefreshCcw,
  shovel: Shovel,
  star: Star,
  thermometerSun: ThermometerSun,
  waves: Waves,
} satisfies Record<IconName, LucideIcon>;
